version: '3.8'

services:
  nsqlookupd:
    build:
      context: .
      dockerfile: Dockerfile.nsqlookupd
    image: nsq-rust-nsqlookupd:dev
    container_name: nsq-nsqlookupd-dev
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - nsq-network
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    volumes:
      - nsqlookupd-data:/var/lib/nsqlookupd
    command: [
      "nsqlookupd",
      "--tcp-address=0.0.0.0:4160",
      "--http-address=0.0.0.0:4161",
      "--log-level=debug"
    ]

  nsqd:
    build:
      context: .
      dockerfile: Dockerfile.nsqd
    image: nsq-rust-nsqd:dev
    container_name: nsq-nsqd-dev
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - nsq-network
    restart: unless-stopped
    depends_on:
      - nsqlookupd
    environment:
      - RUST_LOG=debug
      - NSQD_TCP_ADDRESS=0.0.0.0:4150
      - NSQD_HTTP_ADDRESS=0.0.0.0:4151
      - NSQD_LOOKUPD_TCP_ADDRESS=nsqlookupd:4160
      - NSQD_LOOKUPD_HTTP_ADDRESS=nsqlookupd:4161
      - NSQD_DATA_PATH=/var/lib/nsqd
    volumes:
      - nsqd-data:/var/lib/nsqd
      - ./config:/etc/nsq:ro
    command: [
      "nsqd",
      "--tcp-address=0.0.0.0:4150",
      "--http-address=0.0.0.0:4151",
      "--lookupd-tcp-address=nsqlookupd:4160",
      "--lookupd-http-address=nsqlookupd:4161",
      "--data-path=/var/lib/nsqd",
      "--log-level=debug"
    ]

  nsqadmin:
    build:
      context: .
      dockerfile: Dockerfile.nsqadmin
    image: nsq-rust-nsqadmin:dev
    container_name: nsq-nsqadmin-dev
    ports:
      - "4171:4171"
    networks:
      - nsq-network
    restart: unless-stopped
    depends_on:
      - nsqlookupd
    environment:
      - RUST_LOG=debug
      - NSQADMIN_HTTP_ADDRESS=0.0.0.0:4171
      - NSQADMIN_LOOKUPD_HTTP_ADDRESS=nsqlookupd:4161
    command: [
      "nsqadmin",
      "--http-address=0.0.0.0:4171",
      "--lookupd-http-address=nsqlookupd:4161",
      "--log-level=debug"
    ]

volumes:
  nsqlookupd-data:
    driver: local
  nsqd-data:
    driver: local

networks:
  nsq-network:
    driver: bridge
